### ISSUE TITLE
Request to update https://aosc.io/repo/

### ISSUE THREAD

**Issue by Nyovelt** [AOSC-Dev/aosc-portal-kiss.github.io#48]
The URL of GeekPie Association has been changed in this [pr](https://github.com/AOSC-Dev/aosc-portal-kiss.github.io/pull/47). However, the webpage hasn't been updated, which may encounter some problem in the future since the URL is out-dated.

**Comment by MingcongBai** [comment]
Seems to be resolved. Closing.
