### ISSUE TITLE
Unable to access photo albums in the gallery.

### ISSUE THREAD

**Issue by misaka4e21** [AOSC-Dev/aosc-portal-kiss.github.io#5]
https://aosc.io/news/gallery/

![firefox network tab](https://user-images.githubusercontent.com/1625861/79034084-e650be80-7be5-11ea-9c24-f1aa0b8a589d.png)

**Comment by MingcongBai** [comment]
@misaka4e21 Same here on iOS 13.4, Safari.

**Comment by liushuyu** [comment]
This is due to missing image assets. Thoese assets were deleted after the Hugo migration. They have been restored now.
